name: "Main Workflow"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t sample-website:latest .
      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ secrets.GITHUB_ACTOR }} --password-stdin
          echo "Capital docker name to simple lowercase"
          ImageName=$(echo "sample-website" | tr '[:upper:]' '[:lower:]')
          docker tag sample-website:latest ${{ secrets.GITHUB_ACTOR }}/$ImageName:latest
          docker push ${{ secrets.GITHUB_ACTOR }}/$ImageName:latest